config/routes.rb
Rails.application.routes.draw do
	get '/home/index'
	root 'home#index'

	resources :products, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :unions
	has_many :products, through: :unions
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :unions
	has_many :categories, through: :unions
end

app/models/union.rb
class Union < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
		@categories = Category.all
	end

	def new
		@product = Product.new
		@categories = Category.all
	end

	def edit
		@product = Product.find(params[:id])
		@categories = Category.all
	end

	def create
		@product = Product.new(product_params)
		
		params[:category_ids].each do |id|
			@product.categories << Category.find(id)
		end

		@product.save
		redirect_to action: "index"
	end

	def update
		@product = Product.find(params[:id])
		categories = Category.all

		categories.each do |category|
			if @product.categories.exists?("#{category.id}")
				@product.categories.delete("#{category.id}")
			end
		end

		if params[:category_ids] != nil
			params[:category_ids].each do |id|
				@product.categories << Category.find(id)
			end
		end

		@product.update(product_params)
		redirect_to action: "index"
	end

	private
		def product_params
			params.require(:product).permit(:name, :price, category_ids: [])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class= "jumbotron"><h1>TE AMO SARA</h1></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Products</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<div class="container">
	<div class="col-xl-6 col-lg-6 col-md-6 col-sm-10 col-10">
		<div class="row">
			<h1>Editar producto</h1>
		</div>
		<div class="row">
			<!-- -->
			<%= form_for(@product, url: product_path) do |form| %>
				<div class="form-group">
					<%= form.text_field :name, placeholder: "Nombre", class: "form-control" %>
				</div>
				<div class="form-group">
					<%= form.text_field :price, placeholder: "Precio", class: "form-control" %>
				</div>
				<div class="form_group">
					<ul>
						<% @categories.each do |category| %>
							<li>
								<% if @product.categories.exists?("#{category.id}") %>
									<% check = true %>
								<% else %>
									<% check = false %>
								<% end %>
								<%= check_box_tag "category_ids[]", category.id, check%>
								<%= category.name %>
							</li>
						<% end %> 
					</ul>
				</div>
				<%= form.submit 'Editar producto', class: 'btn btn-primary btn-block' %>
			<% end %>
		</div>
	</div>
</div>

app/views/products/index.html.erb
<div class="container">
		<div class="row">
			<h1>Products</h1>
		</div>
		<div class="row">
			<%= link_to 'Nuevo producto', new_product_path, class: 'btn btn-primary btn-lg col-md-3' %>
		</div>
		<div class="row">
			<table class="table">
				<thead>
					<tr>
						<th>Name</th>
						<th>Price</th>
						<th>category</th>
						<th></th>
					</tr>
				</thead>
				<% @products.each do |product| %>
					<tr>
						<td><%= product.name %></td>
						<td><%= product.price %></td>
						<td>
							<% product.categories.each do |category| %>
								<%= category.name %>
							<% end %>
						</td>
						<td>
							<%= link_to 'Editar', edit_product_path(product) %>&nbsp
							<%= link_to 'Eliminar', '#' %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>

app/views/products/new.html.erb
<div class="container">
	<div class="col-xl-6 col-lg-6 col-md-6 col-sm-10 col-10">
		<div class="row">
			<h1>Nuevo producto</h1>
		</div>
		<div class="row">
			<!-- -->
			<%= form_for(@product) do |form| %>
				<div class="form-group">
					<%= form.text_field :name, placeholder: "Nombre", class: "form-control" %>
				</div>
				<div class="form-group">
					<%= form.text_field :price, placeholder: "Precio", class: "form-control" %>
				</div>
				<div class="form_group">
					<ul>
						<% @categories.each do |category| %>
							<li>
								<%= check_box_tag "category_ids[]", category.id  %>
								<%= category.name %>
							</li>
						<% end %> 
					</ul>
				</div>
				<%= form.submit 'Nuevo producto', class: 'btn btn-primary btn-block' %>
			<% end %>
		</div>
	</div>
</div>